(define-module (emacs emacs-mu4e-folding)
  #:use-module (gnu packages)
  #:use-module (gnu packages linux)
  #:use-module (gnu packages emacs)
  #:use-module (gnu packages mail)
  #:use-module (gnu packages emacs-xyz)
  #:use-module (gnu packages freedesktop)
  #:use-module (gnu packages pkg-config)
  #:use-module (gnu packages xdisorg)

  #:use-module (srfi srfi-1)

  #:use-module (guix diagnostics)
  #:use-module (guix i18n)
  #:use-module (guix packages)
  #:use-module (guix gexp)
  #:use-module (guix git-download)
  #:use-module (guix build-system meson)
  #:use-module (guix build-system emacs)
  #:use-module (guix build-system trivial)
  #:use-module ((guix licenses) #:prefix license:))

(define-public emacs-mu4e-folding
  (package
   (name "emacs-mu4e-folding")
   (version "cfb000")
   (source
    (origin
     (method git-fetch)
     (uri (git-reference
           (url "https://github.com/rougier/mu4e-folding")
           (commit "cfb00099b08a06b2b17891270442b695ca29020f")))
     (sha256
      (base32
       "19paawsrr12mqibzg587n2z5m8zbhfjmv0mk7gbq3x9ayd6bldqb"))))
   (build-system emacs-build-system)
   (propagated-inputs (list mu ))
   (home-page "https://github.com/rougier/mu4e-folding")
   (synopsis "Autogenerated package")
   (description "Autogenerated package")
   (license #f)
   ))
emacs-mu4e-folding
