(define-module (emacs emacs-nano-modeline)
  #:use-module (gnu packages)
  #:use-module (gnu packages linux)
  #:use-module (gnu packages emacs)
  #:use-module (gnu packages emacs-xyz)
  #:use-module (gnu packages freedesktop)
  #:use-module (gnu packages pkg-config)
  #:use-module (gnu packages xdisorg)

  #:use-module (srfi srfi-1)

  #:use-module (guix diagnostics)
  #:use-module (guix i18n)
  #:use-module (guix packages)
  #:use-module (guix gexp)
  #:use-module (guix git-download)
  #:use-module (guix build-system meson)
  #:use-module (guix build-system emacs)
  #:use-module (guix build-system trivial)
  #:use-module ((guix licenses) #:prefix license:))

(define-public emacs-nano-modeline
  (package
   (name "emacs-nano-modeline")
   (version "823161")
   (source
    (origin
     (method git-fetch)
     (uri (git-reference
           (url "https://github.com/rougier/nano-modeline")
           (commit "823161c8894996e5c8375249f467a422579a2947")))
     (sha256
      (base32
       "1g59g1r7gs1pz7wbh07k9p47qp7fygd1gc5kwbd0s5w42zhc6mid"))))
   (build-system emacs-build-system)
   (propagated-inputs (list ))
   (home-page "https://github.com/rougier/nano-modeline")
   (synopsis "Autogenerated package")
   (description "Autogenerated package")
   (license #f)
   ))
emacs-nano-modeline
