(define-module (emacs emacs-nano-theme)
  #:use-module (gnu packages)
  #:use-module (gnu packages linux)
  #:use-module (gnu packages emacs)
  #:use-module (gnu packages emacs-xyz)
  #:use-module (gnu packages freedesktop)
  #:use-module (gnu packages pkg-config)
  #:use-module (gnu packages xdisorg)

  #:use-module (srfi srfi-1)

  #:use-module (guix diagnostics)
  #:use-module (guix i18n)
  #:use-module (guix packages)
  #:use-module (guix gexp)
  #:use-module (guix git-download)
  #:use-module (guix build-system meson)
  #:use-module (guix build-system emacs)
  #:use-module (guix build-system trivial)
  #:use-module ((guix licenses) #:prefix license:))

(define-public emacs-nano-theme
  (package
   (name "emacs-nano-theme")
   (version "8da336")
   (source
    (origin
     (method git-fetch)
     (uri (git-reference
           (url "https://github.com/rougier/nano-theme")
           (commit "8da336cbce57facfb29f13982c93fbc547fae5a1")))
     (sha256
      (base32
       "03afjzl41h9njx5a1bbzqyy5y5w6jq32wk4qhi786kxir9hqy51n"))))
   (build-system emacs-build-system)
   (propagated-inputs (list ))
   (home-page "https://github.com/rougier/nano-theme")
   (synopsis "Autogenerated package")
   (description "Autogenerated package")
   (license #f)
   ))
emacs-nano-theme
