(define-module (emacs emacs-mu4e-dashboard)
  #:use-module (gnu packages)
  #:use-module (gnu packages linux)
  #:use-module (gnu packages emacs)
  #:use-module (gnu packages emacs-xyz)
  #:use-module (gnu packages mail)
  #:use-module (gnu packages freedesktop)
  #:use-module (gnu packages pkg-config)
  #:use-module (gnu packages xdisorg)

  #:use-module (srfi srfi-1)

  #:use-module (guix diagnostics)
  #:use-module (guix i18n)
  #:use-module (guix packages)
  #:use-module (guix gexp)
  #:use-module (guix git-download)
  #:use-module (guix build-system meson)
  #:use-module (guix build-system emacs)
  #:use-module (guix build-system trivial)
  #:use-module ((guix licenses) #:prefix license:))

(define-public emacs-mu4e-dashboard
  (package
   (name "emacs-mu4e-dashboard")
   (version "a7bd92")
   (source
    (origin
     (method git-fetch)
     (uri (git-reference
           (url "https://github.com/rougier/mu4e-dashboard")
           (commit "a7bd92334ac02f45b045911b566a428ee98b322b")))
     (sha256
      (base32
       "1d1fd4ahpkaynv1gkbqfi9k2yijlnh4pskg1kwy1gaq3nvva0da3"))))
   (build-system emacs-build-system)
   (propagated-inputs (list mu ))
   (home-page "https://github.com/rougier/mu4e-dashboard")
   (synopsis "Autogenerated package")
   (description "Autogenerated package")
   (license #f)
   ))
emacs-mu4e-dashboard
